In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/personal-key-indicators-of-heart-disease/2020/heart_2020_cleaned.csv
/kaggle/input/personal-key-indicators-of-heart-disease/2022/heart_2022_with_nans.csv
/kaggle/input/personal-key-indicators-of-heart-disease/2022/heart_2022_no_nans.csv

## Loading Dataset

In [2]:
df = pd.read_csv('/kaggle/input/personal-key-indicators-of-heart-disease/2022/heart_2022_with_nans.csv')

## Exporting necessary Libraries

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import  OrdinalEncoder,OneHotEncoder,LabelEncoder
from sklearn.preprocessing import MinMaxScaler

## Exploring Data

In [4]:
df.head()

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,No,8.0,NaN,No,...,NaN,NaN,NaN,No,No,Yes,No,"Yes, received tetanus shot but not sure what type",No,No
1,Alabama,Female,Excellent,0.0,0.0,NaN,No,6.0,NaN,No,...,1.60,68.04,26.57,No,No,No,No,"No, did not receive any tetanus shot in the pa...",No,No
2,Alabama,Female,Very good,2.0,3.0,Within past year (anytime less than 12 months ...,Yes,5.0,NaN,No,...,1.57,63.50,25.61,No,No,No,No,NaN,No,Yes
3,Alabama,Female,Excellent,0.0,0.0,Within past year (anytime less than 12 months ...,Yes,7.0,NaN,No,...,1.65,63.50,23.30,No,No,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,No
4,Alabama,Female,Fair,2.0,0.0,Within past year (anytime less than 12 months ...,Yes,9.0,NaN,No,...,1.57,53.98,21.77,Yes,No,No,Yes,"No, did not receive any tetanus shot in the pa...",No,No

In [5]:
df.shape

(445132, 40)

# Handle Missing Values

## Identify Missing Values

In [6]:
df.isnull().sum()

State                            0
Sex                              0
GeneralHealth                 1198
PhysicalHealthDays           10927
MentalHealthDays              9067
LastCheckupTime               8308
PhysicalActivities            1093
SleepHours                    5453
RemovedTeeth                 11360
HadHeartAttack                3065
HadAngina                     4405
HadStroke                     1557
HadAsthma                     1773
HadSkinCancer                 3143
HadCOPD                       2219
HadDepressiveDisorder         2812
HadKidneyDisease              1926
HadArthritis                  2633
HadDiabetes                   1087
DeafOrHardOfHearing          20647
BlindOrVisionDifficulty      21564
DifficultyConcentrating      24240
DifficultyWalking            24012
DifficultyDressingBathing    23915
DifficultyErrands            25656
SmokerStatus                 35462
ECigaretteUsage              35660
ChestScan                    56046
RaceEthnicityCategory        14057
AgeCategory                   9079
HeightInMeters               28652
WeightInKilograms            42078
BMI                          48806
AlcoholDrinkers              46574
HIVTesting                   66127
FluVaxLast12                 47121
PneumoVaxEver                77040
TetanusLast10Tdap            82516
HighRiskLastYear             50623
CovidPos                     50764
dtype: int64

## Identify numerical and categorical columns

In [7]:
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
cat_cols = df.select_dtypes(include=['object']).columns

## Imputing Missing Values

In [8]:
for col in num_cols:
    df[col] = df[col].fillna(df[col].mean())

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [9]:
df.isnull().sum()

State                        0
Sex                          0
GeneralHealth                0
PhysicalHealthDays           0
MentalHealthDays             0
LastCheckupTime              0
PhysicalActivities           0
SleepHours                   0
RemovedTeeth                 0
HadHeartAttack               0
HadAngina                    0
HadStroke                    0
HadAsthma                    0
HadSkinCancer                0
HadCOPD                      0
HadDepressiveDisorder        0
HadKidneyDisease             0
HadArthritis                 0
HadDiabetes                  0
DeafOrHardOfHearing          0
BlindOrVisionDifficulty      0
DifficultyConcentrating      0
DifficultyWalking            0
DifficultyDressingBathing    0
DifficultyErrands            0
SmokerStatus                 0
ECigaretteUsage              0
ChestScan                    0
RaceEthnicityCategory        0
AgeCategory                  0
HeightInMeters               0
WeightInKilograms            0
BMI                          0
AlcoholDrinkers              0
HIVTesting                   0
FluVaxLast12                 0
PneumoVaxEver                0
TetanusLast10Tdap            0
HighRiskLastYear             0
CovidPos                     0
dtype: int64

# Dropping Uncessary Column

In [10]:
df = df.drop(columns=['RemovedTeeth'])

# Encoding Categorical Variables

## Identify Categorical Columns

In [11]:
cat_cols = df.select_dtypes(include=['object']).columns

print("Categorical columns:", cat_cols)

Categorical columns: Index(['State', 'Sex', 'GeneralHealth', 'LastCheckupTime',
       'PhysicalActivities', 'HadHeartAttack', 'HadAngina', 'HadStroke',
       'HadAsthma', 'HadSkinCancer', 'HadCOPD', 'HadDepressiveDisorder',
       'HadKidneyDisease', 'HadArthritis', 'HadDiabetes',
       'DeafOrHardOfHearing', 'BlindOrVisionDifficulty',
       'DifficultyConcentrating', 'DifficultyWalking',
       'DifficultyDressingBathing', 'DifficultyErrands', 'SmokerStatus',
       'ECigaretteUsage', 'ChestScan', 'RaceEthnicityCategory', 'AgeCategory',
       'AlcoholDrinkers', 'HIVTesting', 'FluVaxLast12', 'PneumoVaxEver',
       'TetanusLast10Tdap', 'HighRiskLastYear', 'CovidPos'],
      dtype='object')

In [12]:
for col in cat_cols:
    unique_values = df[col].unique()
    print(f"Unique values in '{col}':", unique_values)

Unique values in 'State': ['Alabama' 'Alaska' 'Arizona' 'Arkansas' 'California' 'Colorado'
 'Connecticut' 'Delaware' 'District of Columbia' 'Florida' 'Georgia'
 'Hawaii' 'Idaho' 'Illinois' 'Indiana' 'Iowa' 'Kansas' 'Kentucky'
 'Louisiana' 'Maine' 'Maryland' 'Massachusetts' 'Michigan' 'Minnesota'
 'Mississippi' 'Missouri' 'Montana' 'Nebraska' 'Nevada' 'New Hampshire'
 'New Jersey' 'New Mexico' 'New York' 'North Carolina' 'North Dakota'
 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania' 'Rhode Island' 'South Carolina'
 'South Dakota' 'Tennessee' 'Texas' 'Utah' 'Vermont' 'Virginia'
 'Washington' 'West Virginia' 'Wisconsin' 'Wyoming' 'Guam' 'Puerto Rico'
 'Virgin Islands']
Unique values in 'Sex': ['Female' 'Male']
Unique values in 'GeneralHealth': ['Very good' 'Excellent' 'Fair' 'Poor' 'Good']
Unique values in 'LastCheckupTime': ['Within past year (anytime less than 12 months ago)'
 'Within past 2 years (1 year but less than 2 years ago)'
 'Within past 5 years (2 years but less than 5 years ago)'
 '5 or more years ago']
Unique values in 'PhysicalActivities': ['No' 'Yes']
Unique values in 'HadHeartAttack': ['No' 'Yes']
Unique values in 'HadAngina': ['No' 'Yes']
Unique values in 'HadStroke': ['No' 'Yes']
Unique values in 'HadAsthma': ['No' 'Yes']
Unique values in 'HadSkinCancer': ['No' 'Yes']
Unique values in 'HadCOPD': ['No' 'Yes']
Unique values in 'HadDepressiveDisorder': ['No' 'Yes']
Unique values in 'HadKidneyDisease': ['No' 'Yes']
Unique values in 'HadArthritis': ['No' 'Yes']
Unique values in 'HadDiabetes': ['Yes' 'No' 'No, pre-diabetes or borderline diabetes'
 'Yes, but only during pregnancy (female)']
Unique values in 'DeafOrHardOfHearing': ['No' 'Yes']
Unique values in 'BlindOrVisionDifficulty': ['No' 'Yes']
Unique values in 'DifficultyConcentrating': ['No' 'Yes']
Unique values in 'DifficultyWalking': ['No' 'Yes']
Unique values in 'DifficultyDressingBathing': ['No' 'Yes']
Unique values in 'DifficultyErrands': ['No' 'Yes']
Unique values in 'SmokerStatus': ['Never smoked' 'Current smoker - now smokes some days' 'Former smoker'
 'Current smoker - now smokes every day']
Unique values in 'ECigaretteUsage': ['Not at all (right now)' 'Never used e-cigarettes in my entire life'
 'Use them every day' 'Use them some days']
Unique values in 'ChestScan': ['No' 'Yes']
Unique values in 'RaceEthnicityCategory': ['White only, Non-Hispanic' 'Black only, Non-Hispanic'
 'Other race only, Non-Hispanic' 'Multiracial, Non-Hispanic' 'Hispanic']
Unique values in 'AgeCategory': ['Age 80 or older' 'Age 55 to 59' 'Age 65 to 69' 'Age 40 to 44'
 'Age 75 to 79' 'Age 70 to 74' 'Age 60 to 64' 'Age 50 to 54'
 'Age 45 to 49' 'Age 35 to 39' 'Age 25 to 29' 'Age 30 to 34'
 'Age 18 to 24']
Unique values in 'AlcoholDrinkers': ['No' 'Yes']
Unique values in 'HIVTesting': ['No' 'Yes']
Unique values in 'FluVaxLast12': ['Yes' 'No']
Unique values in 'PneumoVaxEver': ['No' 'Yes']
Unique values in 'TetanusLast10Tdap': ['Yes, received tetanus shot but not sure what type'
 'No, did not receive any tetanus shot in the past 10 years'
 'Yes, received Tdap' 'Yes, received tetanus shot, but not Tdap']
Unique values in 'HighRiskLastYear': ['No' 'Yes']
Unique values in 'CovidPos': ['No' 'Yes'
 'Tested positive using home test without a health professional']

## For Ordinal Categories

In [13]:
ordinal_categories = [['Poor', 'Fair', 'Good', 'Very good', 'Excellent']]
ordinal_col = 'GeneralHealth'

# Apply Ordinal Encoding
ordinal_encoder = OrdinalEncoder(categories=ordinal_categories)
df[ordinal_col] = ordinal_encoder.fit_transform(df[[ordinal_col]])

# Display the DataFrame
print(df)

                 State     Sex  GeneralHealth  PhysicalHealthDays  \
0              Alabama  Female            3.0                 0.0
1              Alabama  Female            4.0                 0.0
2              Alabama  Female            3.0                 2.0
3              Alabama  Female            4.0                 0.0
4              Alabama  Female            1.0                 2.0
...                ...     ...            ...                 ...
445127  Virgin Islands  Female            2.0                 0.0
445128  Virgin Islands  Female            4.0                 2.0
445129  Virgin Islands  Female            0.0                30.0
445130  Virgin Islands    Male            3.0                 0.0
445131  Virgin Islands    Male            3.0                 0.0

        MentalHealthDays                                    LastCheckupTime  \
0                    0.0  Within past year (anytime less than 12 months ...
1                    0.0  Within past year (anytime less than 12 months ...
2                    3.0  Within past year (anytime less than 12 months ...
3                    0.0  Within past year (anytime less than 12 months ...
4                    0.0  Within past year (anytime less than 12 months ...
...                  ...                                                ...
445127               3.0  Within past 2 years (1 year but less than 2 ye...
445128               2.0  Within past year (anytime less than 12 months ...
445129              30.0                                5 or more years ago
445130               0.0  Within past year (anytime less than 12 months ...
445131               1.0  Within past year (anytime less than 12 months ...

       PhysicalActivities  SleepHours HadHeartAttack HadAngina  ...  \
0                      No         8.0             No        No  ...
1                      No         6.0             No        No  ...
2                     Yes         5.0             No        No  ...
3                     Yes         7.0             No        No  ...
4                     Yes         9.0             No        No  ...
...                   ...         ...            ...       ...  ...
445127                Yes         6.0             No        No  ...
445128                Yes         7.0             No        No  ...
445129                 No         5.0             No        No  ...
445130                 No         5.0            Yes        No  ...
445131                Yes         5.0             No        No  ...

       HeightInMeters WeightInKilograms        BMI AlcoholDrinkers HIVTesting  \
0            1.702691          83.07447  28.529842              No         No
1            1.600000          68.04000  26.570000              No         No
2            1.570000          63.50000  25.610000              No         No
3            1.650000          63.50000  23.300000              No         No
4            1.570000          53.98000  21.770000             Yes         No
...               ...               ...        ...             ...        ...
445127       1.650000          69.85000  25.630000             Yes        Yes
445128       1.700000          83.01000  28.660000              No        Yes
445129       1.700000          49.90000  17.230000             Yes         No
445130       1.830000         108.86000  32.550000              No        Yes
445131       1.680000          63.50000  22.600000             Yes         No

       FluVaxLast12 PneumoVaxEver  \
0               Yes            No
1                No            No
2                No            No
3               Yes           Yes
4                No           Yes
...             ...           ...
445127           No            No
445128          Yes            No
445129           No            No
445130          Yes           Yes
445131           No            No

                                        TetanusLast10Tdap HighRiskLastYear  \
0       Yes, received tetanus shot but not sure what type               No
1       No, did not receive any tetanus shot in the pa...               No
2       No, did not receive any tetanus shot in the pa...               No
3       No, did not receive any tetanus shot in the pa...               No
4       No, did not receive any tetanus shot in the pa...               No
...                                                   ...              ...
445127  No, did not receive any tetanus shot in the pa...               No
445128  Yes, received tetanus shot but not sure what type               No
445129  No, did not receive any tetanus shot in the pa...               No
445130  No, did not receive any tetanus shot in the pa...               No
445131  Yes, received tetanus shot but not sure what type               No

       CovidPos
0            No
1            No
2           Yes
3            No
4            No
...         ...
445127      Yes
445128       No
445129       No
445130      Yes
445131       No

[445132 rows x 39 columns]

## For Nominal Categories

In [14]:
selected_cat_cols = ['Sex', 'HadCOPD', 'State']

df[selected_cat_cols] = df[selected_cat_cols].astype(str)

onehot_encoder = OneHotEncoder(sparse=False, handle_unknown='ignore')
onehot_encoded = onehot_encoder.fit_transform(df[selected_cat_cols])

onehot_encoded_df = pd.DataFrame(onehot_encoded, columns=onehot_encoder.get_feature_names_out(selected_cat_cols))

df = df.drop(selected_cat_cols, axis=1).reset_index(drop=True)
onehot_encoded_df = onehot_encoded_df.reset_index(drop=True)

df = pd.concat([df, onehot_encoded_df], axis=1)

df.head()

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,HadHeartAttack,HadAngina,HadStroke,HadAsthma,...,State_Tennessee,State_Texas,State_Utah,State_Vermont,State_Virgin Islands,State_Virginia,State_Washington,State_West Virginia,State_Wisconsin,State_Wyoming
0,3.0,0.0,0.0,Within past year (anytime less than 12 months ...,No,8.0,No,No,No,No,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,4.0,0.0,0.0,Within past year (anytime less than 12 months ...,No,6.0,No,No,No,No,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3.0,2.0,3.0,Within past year (anytime less than 12 months ...,Yes,5.0,No,No,No,No,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4.0,0.0,0.0,Within past year (anytime less than 12 months ...,Yes,7.0,No,No,No,Yes,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,2.0,0.0,Within past year (anytime less than 12 months ...,Yes,9.0,No,No,No,No,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Label Encoding

In [15]:
label_encoder = LabelEncoder()
df['HadHeartAttack'] = label_encoder.fit_transform(df['HadHeartAttack'])

# Feature Scaling

## Min-Max Scaling

In [16]:
num_cols = df.select_dtypes(include=['int64', 'float64']).columns

min_max_scaler = MinMaxScaler()
df[num_cols] = min_max_scaler.fit_transform(df[num_cols])

print(df.head())

   GeneralHealth  PhysicalHealthDays  MentalHealthDays  \
0           0.75            0.000000               0.0
1           1.00            0.000000               0.0
2           0.75            0.066667               0.1
3           1.00            0.000000               0.0
4           0.25            0.066667               0.0

                                     LastCheckupTime PhysicalActivities  \
0  Within past year (anytime less than 12 months ...                 No
1  Within past year (anytime less than 12 months ...                 No
2  Within past year (anytime less than 12 months ...                Yes
3  Within past year (anytime less than 12 months ...                Yes
4  Within past year (anytime less than 12 months ...                Yes

   SleepHours  HadHeartAttack HadAngina HadStroke HadAsthma  ...  \
0    0.304348             0.0        No        No        No  ...
1    0.217391             0.0        No        No        No  ...
2    0.173913             0.0        No        No        No  ...
3    0.260870             0.0        No        No       Yes  ...
4    0.347826             0.0        No        No        No  ...

  State_Tennessee State_Texas State_Utah State_Vermont State_Virgin Islands  \
0             0.0         0.0        0.0           0.0                  0.0
1             0.0         0.0        0.0           0.0                  0.0
2             0.0         0.0        0.0           0.0                  0.0
3             0.0         0.0        0.0           0.0                  0.0
4             0.0         0.0        0.0           0.0                  0.0

  State_Virginia State_Washington State_West Virginia State_Wisconsin  \
0            0.0              0.0                 0.0             0.0
1            0.0              0.0                 0.0             0.0
2            0.0              0.0                 0.0             0.0
3            0.0              0.0                 0.0             0.0
4            0.0              0.0                 0.0             0.0

  State_Wyoming
0           0.0
1           0.0
2           0.0
3           0.0
4           0.0

[5 rows x 94 columns]

# Splitting the Dataset

In [17]:
X = df.drop('HadHeartAttack', axis=1) 
y = df['HadHeartAttack']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Display the shapes of the resulting datasets
print(f'Training set shape: X={X_train.shape}, y={y_train.shape}')
print(f'Testing set shape: X={X_test.shape}, y={y_test.shape}')

Training set shape: X=(356105, 93), y=(356105,)
Testing set shape: X=(89027, 93), y=(89027,)